architecture:
  name: pyannote.audio.models.PyanNet
  params:
    ff:
      hidden_size:
      - 128
      - 128
    rnn:
      bidirectional: true
      dropout: 0
      hidden_size: 128
      num_layers: 3
      unit: LSTM
    sincnet:
      kernel_size:
      - 251
      - 5
      - 5
      out_channels:
      - 256
      - 60
      - 60
feature_extraction:
  name: RawAudio
  params:
    sample_rate: 16000
scheduler:
  name: CyclicScheduler
  params:
    epochs_per_cycle: 14
    learning_rate: auto
task:
  name: MultilabelDetection
  params:
    batch_size: 64
    duration: 2.0
    labels_spec:
      regular:
      - KCHI
      - CHI
      - MAL
      - FEM
      - SPEECH
    per_epoch: 1